### ISSUE TITLE
Adds stats

### ISSUE THREAD

**Issue by dominicbarnes** [segmentio/go-slacker#17]
Without any stats, it's really hard to know when a command goes unused, how often errors occur, etc. Since this is a private module, maybe we can add `kit/logger` so we can start tracking this stuff.

**Comment by f2prateek** [comment]
Just made this open source!

Easy enough to do with a middleware:

``` go
type Handler struct {
  delegate slacker.Handler
}

func (h *Handler) HandleCommand(w io.Writer, c *Command) error {
  // stats/logging etc.
  err := delegate.HandleCommand(w, c)
  if err != nil {
    // track error
  }
  return err
}
```
